
FIND_PATH(GLEW_INCLUDE_DIRS GL HINTS ${CMAKE_SOURCE_DIR}/../../glew/include)
FIND_PATH(GLEW_LIB_DIR glew.lib HINTS ${CMAKE_SOURCE_DIR}/../../glew/lib)
SET(GLEW_DEBUG_LIB ${GLEW_LIB_DIR}/glewd.lib)
SET(GLEW_RELEASE_LIB ${GLEW_LIB_DIR}/glew.lib)