
FIND_PATH(CERES_INCLUDE_DIRS ceres HINTS ${CMAKE_SOURCE_DIR}/../../Ceres/include)
FIND_PATH(CERES_LIB_DIR ceres.lib HINTS ${CMAKE_SOURCE_DIR}/../../Ceres/lib)
SET(CERES_DEBUG_LIB ${CERES_LIB_DIR}/ceres-debug.lib)
SET(CERES_RELEASE_LIB ${CERES_LIB_DIR}/ceres.lib)